# Generated by Django 5.2 on 2025-06-20 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_subject_alter_option_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='labels',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
