# Generated by Django 5.2.3 on 2025-06-23 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_certification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='passing_marks',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='total_marks',
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_percentage',
            field=models.PositiveIntegerField(default=60, help_text='Passing percentage (e.g. 60 for 60%)'),
        ),
    ]
